[package]
name = "log-derive"
version = "0.1.0"
edition = "2018"
authors = ["Elichai <elichai.turkel@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/elichai/log-derive"
description = "Procedural Macro for logging result of a function"
categories = ["development-tools::debugging"]
keywords = ["log", "macro", "derive", "logging", "function"]

[dependencies]
proc-macro2 = "0.4"
syn = { version = "0.15", features = ["full", "extra-traits"] }
quote = "0.6"
log = "0.4"

[lib]
proc-macro = true